[package]
name = "whatsmeow-sys"
version.workspace = true
edition.workspace = true
description = "Raw FFI bindings to WhatsApp Go bridge"

[build-dependencies]
cc = "1.0"

[dependencies]
libc.workspace = true
